apiVersion: v1
kind: Template
metadata:
  name: is-template
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_NAME}
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: "philipfoster/hello-openshift:latest"

parameters:
  - name: APP_NAME
    required: true
    description: The app name